### ISSUE TITLE
Islamic calendar not correct

### ISSUE THREAD

**Issue by MenoData** [hypotemoose/almanac-converter#8]
Two observations:

- The islamic year has often more than 354 days but your calendar fixes the count to always 354.
- Unfortunately your calendar is not configurable allowing varying lengths of islamic months (see also the official calendar of Saudi-Arabi named Umalqura or other regional sighting-based variants).

For comparison, see also my implementation of [HijriCalendar](https://github.com/MenoData/Time4J/blob/master/calendar/src/main/java/net/time4j/calendar/HijriCalendar.java).

**Comment by chrisengelsma** [comment]
Good catch! I hadn't realized that 354 was hardwired in there, seems like an easy fix, and also extending the month lengths is another oversight. Thanks for the feedback!

**Comment by chrisengelsma** [comment]
I'm going to mark this as closed - the code has now been updated to support 4 leap-year patterns, as well as civil versus astronomical calendar epochs.

Regarding the umm al-qura saudi calendar - I'm going to kick that can down the road for the time being as this calendar is strictly tabular, but it's something i'll possibly consider tackling in the future.
